import type { PropertyCard } from "./rooms-section.types";

export const filters = [
	{
		label: "City",
		options: ["Pune", "Mumbai"],
	},
	{
		label: "Location",
		options: [
			"Baner",
			"Balewadi",
			"Mundhwa",
			"Mulshi",
			"Yerwada",
			"Karve Nagar",
			"Kothrud",
			"SB Road",
			"Shivaji Nagar",
			"Hinjewadi",
			"Mahalunge",
			"Bhosari",
		],
	},
	{
		label: "Gender",
		options: ["Male", "Female", "Other"],
	},
	{
		label: "Accommodation Type",
		options: ["Student housing", "Co-living"],
	},
];

export const properties: PropertyCard[] = [
	{
		id: "yv-balewadi-1",
		name: "Youthville Balewadi-1",
		location: "Pune",
		area: "Balewadi",
		gender:["Male","Female"],
		type: "Private and shared Room",
		price: "₹16,500/-",
		badge: "STUDENT HOUSING",
		badgeVariant: "Co-living",
		image: "/property/balewadi-1/cover.png",
		available: true,
	},
	{
		id: "yv-balewadi-2",
		name: "Youthville Balewadi-2",
		location: "Pune",
		area: "Balewadi",
		gender:["Male","Female"],
		type: "Private and shared Room",
		price: "₹18,000/-",
		badge: "CO-LIVING",
		badgeVariant: "Co-living",
		image: "/property/balewadi-2/cover.png",
		available: true,
	},
	{
		id: "yv-kiwale",
		name: "Youthville Kiwale",
		location: "Pune",
		area: "Kiwale",
		gender:["Male","Female"],
		type: "Private and shared Room",
		price: "₹21,000/-",
		badge: "STUDENT HOUSING",
		badgeVariant: "Student",
		image: "/property/kiwale/cover.png",
		available: true,
	},
	{
		id: "yv-sancheti",
		name: "Youthville Sancheti",
		location: "Pune",
		area: "Sancheti",
		gender: ["Male"],
		type: "Private and shared Room",
		price: "₹30,000/-",
		badge: "CO-LIVING",
		badgeVariant: "Uncategorized",
		image: "/property/sancheti/cover.png",
		available: true,
	},
	{
		id: "yv-yerwada",
		name: "Youthville Yerwada",
		location: "Pune",
		area: "Yerwada",
		gender: ["Male"],
		type: "Private and shared Room",
		price: "₹20,000/-",
		badge: "STUDENT HOUSING",
		badgeVariant: "Uncategorized",
		image: "/home/avif/b1.avif",
		available: true,
	},
	{
		id: "yv-sbr-1",
		name: "Youthville SBR-1",
		location: "Pune",
		area: "SB Road",
		gender: ["Male","Female"],
		type: "Private and shared Room",
		price: "",
		badge: "CO-LIVING",
		badgeVariant: "Student",
		image: "/property/sbr-1/cover.png",
		available: false,
	},
	{
		id: "yv-sbr-2",
		name: "Youthville SBR-2",
		location: "Pune",
		area: "SB Road",
		gender: ["Only Girls"],
		type: "Private and shared Room",
		price: "",
		badge: "Student",
		badgeVariant: "Student",
		image: "/shared/avif/1.avif",
		available: false,
	},
	{
		id: "yv-sbr-3",
		name: "Youthville SBR-3",
		location: "Pune",
		area: "SB Road",
		gender: ["Male","Female"],
		type: "Private and shared Room",
		price: "",
		badge: "CO-LIVING",
		badgeVariant: "Student",
		image: "/property/sbr-3/cover.png",
		available: false,
	},
	{
		id: "yv-karve-nagar",
		name: "Youthville Karve Nagar",
		location: "Pune",
		area: "Karve Nagar",
		gender: ["Female"],
		type: "Private and shared Room",
		price: "",
		badge: "Uncategorized",
		badgeVariant: "Uncategorized",
		image: "/property/karve-nagar/cover.png",
		available: false,
	},
	{
		id: "yv-juhu-jvpd",
		name: "Youthville Juhu- JVPD",
		location: "Mumbai",
		area: "Juhu- JVPD",
		gender: ["Male"],
		type: "Private and shared Room",
		price: "",
		badge: "Uncategorized",
		badgeVariant: "Uncategorized",
		image: "/property/mumbai-juhu/cover.png",
		available: false,
	},
];
